import React from 'react';
import Paper from '@material-ui/core/Paper';

class MyHome extends React.Component
{
  render() {
    return (
      <Paper className = "home" elevation = {20}>
        <div>
        <h1 className = "title">Welcome</h1>
        </div>
        <br/>
        <div className = "text">
          <h4>This is my personal Material-UI and React design reference website, built by React-Redux and Material-UI. </h4>
          <br/>
          <h4>This website includes color design reference, Material-UI component demos, char demos generated by React-vis, and an icon library. Each demo comes with sample code usage. Click left meun to check details. Right menu directs to exteral reference websites.</h4>
          <br/>
          <h4>Material Design is a design language that Google developed in 2014. Expanding on the "card" motifs that debuted in Google Now, Material Design uses more grid-based layouts, responsive animations and transitions, padding, and depth effects such as lighting and shadows.</h4>
          <br/>
         
        </div>
      </Paper>
    )
  }
}
export default MyHome